### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by riskmaris** [GhostEsso/Leaderboard#6]
Well done on your Leaderboard app exercise. Your code looks clean and your use of gitflow is fantastic!
However you can try to improve on the UI especially your submit button. Maybe you can try giving it a dark color for easy visibility.

**Comment by GhostEsso** [comment]
@riskmaris Thank you Maris :pray:

**Comment by faisalakb** [comment]
well done @GhostEsso keep doing good work. Happy coding
